### ISSUE TITLE
2.12-ification

### ISSUE THREAD

**Issue by mosesn** [twitter/bijection#248]
We should start publishing against 2.12.0-M4 if possible, since it looks like 2.12.0 final is around the corner.

**Comment by johnynek** [comment]
I took a stab at this.

Turns out our build is fairly old and like 2 layers of deprecation deep. I think we need to probably need to rewrite most of the build.sbt to get this to work.

The naive thing of just using sbt 13.13 and setting the version to 2.12.0 didn't work.

I got:
https://gitter.im/sbt/sbt?at=581fc9de31c5cbef43c41087

```
[error] Modules were resolved with conflicting cross-version suffixes in {file:/home/oscar-unencrypted/oss/bijection/}bijection-core: 14:23 [error] org.scala-lang.modules:scala-xml _2.11, _2.12
```

I think basically we are hitting some corner case where sbt does not fail explicitly, but since we are using so many deprecated things it actually does not work.

**Comment by mosesn** [comment]
@johnynek have you had a chance to take another look at this?

**Comment by oscar-stripe** [comment]
well, there is a bug with sbt. So, we need to remove the scalafmt plugin, that might fix it. But I have not gone further than that.

**Comment by mosesn** [comment]
thanks for the update @oscar-stripe.

**Comment by clhodapp** [comment]
See https://github.com/twitter/bijection/pull/257

**Comment by sritchie** [comment]
Excellent, looks like that's merged!

**Comment by sritchie** [comment]
@mosesn, any chance we can ask you for a PR now that this seems unblocked?

**Comment by piyushnarang** [comment]
Added a PR to cross build 2.12: https://github.com/twitter/bijection/pull/258. Not super familiar with sbt and the works, so would be great if folks with a better grasp can take a look :-).

**Comment by oscar-stripe** [comment]
looks like this is out and published now, right?

**Comment by piyushnarang** [comment]
@oscar-stripe yes, its out.
