### ISSUE TITLE
connecting bijections for free?

### ISSUE THREAD

**Issue by ShahOdin** [twitter/bijection#278]
If I define implicit bijections 
```
implicit def a2b[A,B] : Bijection[A,B] = ???
implicit def b2c[B,C] : Bijection[B,C] = ???
```
I was hoping I would get a bijection from `A<=>C` for free. that didn't happen. 

To get it explicitly, I initially tried manually composing them and defining:
```
implicit def a2c[A,B,C] = a2b[A,B] andThen b2c[B,C]
```
That works but is a bit tedious. 

I then came across the function `connect`. I tried writing: 
```
implicit def a2c[A,B,C] = connect[A,B,C]
```
but the compiler complained that it did not find `ImplicitBijection[A,B]` etc in scope. why was there a need to have a separate type for the implicits? Regardless, what is the easiest way of getting an implicit `Bijection[A,C]` given `a2b` and `b2c` as above in scope?

**Comment by johnynek** [comment]
The way you have written the above code a2b and b2c are ambiguous because they are both fully generic. That, I think, is the problem. You do need connect or your own implicit version otherwise compilation time is very slow.

Lastly, ImplicitBijection exists to prioritize cases where A to B and B to A both exist. Injection does not have the symmetry in types so does not need that.

Hope these hints help.
